const search = [
  "All Categories",
  "Alexa Skills",
  "Amazon Devices",
  " Amazon Fashion",
  "Amazon Fresh",
  "Amazon Pharmacy",
  "Appliances",
  "App & Games",
  "Baby",
  "Beauty",
  "Books",
  "Car & MotorBike",
  "Clothing & Accessories",
  "Collectibles",
  "Computers & Accessories",
  "Deals",
  "Electronics",
  "Furniture",
  "Garden & Outdoors",
  "Gift Cards",
  "Grocery & Gourmet Foods",
  "Health & Personal Care",
  "Home & Kitchen",
  "Industrial & Scientific",
  "Jewellery",
  "Kindle Store",
  "Luggage & Bags",
  "Luxury Beauty",
  "Movies & TV Shows",
  "Music",
  "Musical Instruments",
  "Office Products",
  "Pet Supplies",
  "Prime Supplies",
  "Prime Video",
  "Shoes & Handbags",
  "Software",
  "Sports, Fitness & Outdoors",
  "Subscribe & Save",
  "Tools & Home Improvement",
  "Toys & Games",
  "Under $25",
  "Video Games",
  "Watches",
];

export default search;
